### ISSUE TITLE
smart shortcuts issue?

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#30]
I did a build of the skin from Git and noticed that something keeps scanning - my favorites?

reason I think that is because I have a favorite that points to update genesis plugin folders and I keep seeing the update happen over - and - over - and - over - and over ... you get the point and I had an old favorite that pointed to an old plugin I no longer have and I was getting errors about it now.

I was just curious if this could be part of your new smart shortcuts?

or if you had anything that would be scanning favorites over and over and over

because the log shows a lot of calls to plugin functions I have favorited,

**Comment by mgonzales71** [comment]
looks like the helper script is scanning favorites:

#get favorites
favoritesCount = 0
fav_file = xbmc.translatePath( 'special://profile/favourites.xml' ).decode("utf-8")
if xbmcvfs.exists( fav_file ):
doc = parse( fav_file )
listing = doc.documentElement.getElementsByTagName( 'favourite' )
for count, favourite in enumerate(listing):
name = favourite.attributes[ 'name' ].nodeValue
path = favourite.childNodes [ 0 ].nodeValue
if path.startswith("ActivateWindow(Videos") or path.startswith("ActivateWindow(10025"):
image = getImageFromPath(path)
if image != None:
win.setProperty("favorite." + str(favoritesCount) + ".image", image)
win.setProperty("favorite." + str(favoritesCount) + ".label", name)
win.setProperty("favorite." + str(favoritesCount) + ".action", path)
favoritesCount += 1

if I remove my favorites.xml file the problem goes away.

just to help you out i will include my favorites file contents.... 

as you can see the scanning is calling alot of plugins over and over...

hopefully this will help you out in solving this issue/bug (feature?) :-)

here is my favorites file:

<favourites>
    <favourite name="My Next Episodes" thumb="C:\Users\Mario\AppData\Roaming\Kodi\addons\plugin.video.salts\art\themes\Shine\my_progress.png">ActivateWindow(10025,&quot;plugin://plugin.video.salts/?mode=show_progress&quot;,return)</favourite>
    <favourite name="Program Add-ons" thumb="C:\Users\Mario\AppData\Roaming\Kodi\media\My backgrounds\apple_desktop-wallpaper-1920x1080.jpg">ActivateWindow(10001,&quot;addons://sources/executable/&quot;,return)</favourite>
    <favourite name="Video Add-ons" thumb="C:\Users\Mario\AppData\Roaming\Kodi\media\My backgrounds\tv shows wall.jpg">ActivateWindow(10025,&quot;library://video/addons.xml/&quot;,return)</favourite>
    <favourite name="Reload Skin" thumb="C:\Users\Mario\AppData\Roaming\Kodi\media\My backgrounds\addons - 3.jpg">ReloadSkin()</favourite>
    <favourite name="Trending TV" thumb="C:\Users\Mario\AppData\Roaming\Kodi\addons\plugin.video.genesis\resources\art\gone\shows_trending.jpg">ActivateWindow(10025,&quot;plugin://plugin.video.genesis/?action=shows_trending&quot;,return)</favourite>
    <favourite name="Trending Movies" thumb="C:\Users\Mario\AppData\Roaming\Kodi\addons\plugin.video.genesis\resources\art\gone\movies_trending.jpg">ActivateWindow(10025,&quot;plugin://plugin.video.genesis/?action=movies_trending&quot;,return)</favourite>
    <favourite name="Picture Add-ons">ActivateWindow(10002,&quot;addons://sources/image/&quot;,return)</favourite>
    <favourite name="Music Add-ons" thumb="C:\Users\Mario\AppData\Roaming\Kodi\media\My backgrounds\Music-smartphone-hd-wallpapers.jpg">ActivateWindow(10501,&quot;addons://sources/audio/&quot;,return)</favourite>
    <favourite name="Playlists" thumb="DefaultVideoPlaylists.png">ActivateWindow(10025,&quot;library://video/playlists.xml/&quot;,return)</favourite>
    <favourite name="John&apos;s Background Switcher">SlideShow(C:\Users\Mario\Pictures\John&apos;s Background Switcher\,recursive,random)</favourite>
    <favourite name="Genesis" thumb="C:\Users\Mario\AppData\Roaming\Kodi\addons\plugin.video.genesis\icon.png">ActivateWindow(10025,&quot;plugin://plugin.video.genesis/&quot;,return)</favourite>
    <favourite name="In progress TV shows" thumb="DefaultInProgressShows.png">ActivateWindow(10025,&quot;library://video/inprogressshows.xml/&quot;,return)</favourite>
    <favourite name="[B]GENESIS[/B] : Update folders..." thumb="C:\Users\Mario\AppData\Roaming\Kodi\addons\plugin.video.genesis\resources/art\metro\library_update.jpg">ActivateWindow(10025,&quot;plugin://plugin.video.genesis/?action=library_update_tool&quot;,return)</favourite>
    <favourite name="ATHF" thumb="C:\Users\Mario\AppData\Roaming\Kodi\media\icons\athf.png">PlayMedia(&quot;plugin://plugin.program.advanced.launcher/?ccf382de6c4f23a817abd9c7c7db2882/5a7d0dddbeea3f9ae12906c99231bf21&quot;)</favourite>
    <favourite name="TGUN" thumb="C:\Users\Mario\AppData\Roaming\Kodi\media\icons\tgun.png">PlayMedia(&quot;plugin://plugin.program.advanced.launcher/?ccf382de6c4f23a817abd9c7c7db2882/ee32d2fb96d38209a1c2bc6ec068971d&quot;)</favourite>
</favourites>

**Comment by marcelveldt** [comment]
Hi Mario,
Yes it's indeed happening because of the new smart shortcuts but it's not finished yet.
I still have to create some on/off toggles. Will do so later today and publish beta after that.
Please be aware that checking out the git is at your own risk, I sometimes check in unfinished stuff ;-)

If you want you can already test the new smart shortcuts...
Create a favorite or playlist to a movies folder. This will be picked up by the background scanner.
If you go to the menu shortcuts edit screen and press Add you'll notice a smart shortcuts section.

Any items in your playlists/favorites that have videocontent will be visible.
If you add it to the homescreen you'll get a tile which automatically shows images from the section and also will the background image.

Give it a try and let me know.

**Comment by mgonzales71** [comment]
Oh - I can live with the issues - I just renamed my favorites file temporarily - once you push the new beta I will restore it to test properly!   :-) hehehe

since git stripped my paste here is the pastebin link to my fav file if it help you with conditions you may have not thought about yet! :)

http://pastebin.com/36qH5j9b

**Comment by mgonzales71** [comment]
I will close this since its unfinished and I was just too eager - once you push I will re-test and report any issues I come across

thanks!

**Comment by marcelveldt** [comment]
Please test with your favoritesfile intact and send me the log...
Once you enable the setting to scan favorites it will behave just the same.. Also in final version

**Comment by marcelveldt** [comment]
I'm going to seperate the setting to enable it for favorites and/or playlists. Currently it's enabled for both by default because I haven't created the setting just yet

**Comment by mgonzales71** [comment]
ok - gimme a couple mins

**Comment by mgonzales71** [comment]
here is log file

http://pastebin.com/UqWNN7xp

these calls:

1)

11:28:01 T:11160  NOTICE: Stream All The Sources: Version: |1.0.0~beta2| Queries: |{'mode': 'show_progress'}|
11:28:01 T:11160  NOTICE: Stream All The Sources: Args: |['plugin://plugin.video.salts/', '3', '?mode=show_progress']|
11:28:01 T:11160  NOTICE: Stream All The Sources: Calling |show_progress| for mode |show_progress| with pos args |[]| and kwargs |{}|

2)

11:28:27 T:10396   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.genesis/?action=library_update_tool

are the ones that are looping over and over...

3)

11:30:46 T:10396 WARNING: XFILE::CDirectoryFactory::Create - unsupported protocol(script) in script://script.navi-x/?content_type=video
11:30:46 T:10396   ERROR: XFILE::CDirectory::Exists - Error checking for script://script.navi-x/?content_type=video
11:30:46 T:10396 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video

not sure about this third one but it seems to repeat over and over with the first two... another looper maybe from my playlist directory?

finally - the calls to just those 2 add-ons drove my network activity up as well - so that could be an issue to note for any defaults you set - I know that genesis does a library scan ever call for update folders in addition to scanning for new tv shows - and that triggers an artwork scan as well :)

let me know if I can send any more info back to help out.

thanks

mario

**Comment by mgonzales71** [comment]
just did a test.

created a favorite of sci-fi genre - went to add new home time - smart shortcuts listed sci-fi.
now i have a home tile that is all sci-fi genre movies - pretty cool - I don't think any skin has ever had this feature!

will you support super-favorites add-on for creating smart shortcuts?

I have always wanted to have a home tile that led to a totally custom list of sources/items under it,.

right now a favorite will only point to one item but only super favorites will let you created a group of custom items,

well - now that I think about it maybe you can create a favorite to a super favorite and do just that!

I will have to test that out!

Mario

**Comment by mgonzales71** [comment]
not that it's a big deal - just noticed the created main tile from a smart shortcut has an empty submenu that pops up

![2015-03-23_11-55-07](https://cloud.githubusercontent.com/assets/6510026/6787967/8c552fac-d153-11e4-81fd-b279f2a849e5.png)

**Comment by marcelveldt** [comment]
yeah, I't's a pretty cool feature huh ? It works with both playlists and video-addons...

For the super favorites: why not enable subpages as your submenu preference ?

**Comment by marcelveldt** [comment]
the empty submenu: please check in shortcut editor if there really are no submenu items added to the shortcut..

**Comment by mgonzales71** [comment]
now I can't get that empty submenu to show up again. weird.

i uninstalled super favorites a while ago but now that I have smart shortcuts and submenu pages I am going to look back into it.

**Comment by marcelveldt** [comment]
OK, I'm about to add two settings to the skin settings:
1) enable smart shortcuts for video playlists
2) enable smart shortcuts for favourites

I'm gonna enable the one for playlists by default. What do you think, should I also enable the favourites one by default ?

**Comment by mgonzales71** [comment]
submenu was empty in editor - but I can't repeat displaying the empty submenu again anyway.

if I had not got a screen shot of it I would doubt I saw it! hehe

Well - can you prevent looping?

what I am afraid of is this:

someone doesn't notice to looping scan - after - scan  and causes internet usage to exceed data caps or something.

either both off by default or just playlists on by default.

at least at first to see what issues come back from the beta testers..

what do you think?

**Comment by marcelveldt** [comment]
yeah, I'm working on the looping thing... will be sorted for sure. 
For now I only enable the playlist version by default because that has been requested the most by users, the favorites thing is just something that popped into my head when working on the playlists feature.

BTW, is this proper english as an explanaition with the feature toggles:

Smart shortcuts will enable a background scanner for supported favourites and playlists. If you add a smart shortcut to your home menu, you'll get auto rotating tile images and backgrounds for that particular section

**Comment by mgonzales71** [comment]
sounds good to me :)

one day it may be necessary to start a titan skin documentation project with so many features that are not typically found it most skins

**Comment by mgonzales71** [comment]
I keep seeing this error repeat now as well:

11:49:03 T:10376   ERROR: XFILE::CDirectory::GetDirectory - Error getting C:\Users\Mario\AppData\Roaming\Kodi\userdata\library\video
11:49:03 T:10376   ERROR: XFILE::CDirectory::GetDirectory - Error getting C:\Users\Mario\AppData\Roaming\Kodi\addons\skin.titan.helix\playlists\
11:49:03 T:10376   ERROR: XFILE::CDirectory::GetDirectory - Error getting special://skin/playlists/

**Comment by marcelveldt** [comment]
it means you don't have any playlists.. I have to add a check for that too :-)

**Comment by mgonzales71** [comment]
I do! :-)

![2015-03-23_12-25-38](https://cloud.githubusercontent.com/assets/6510026/6788595/e4ccb02a-d157-11e4-9ebe-2a4ce3b8b310.png)

it likes 2 of them at least ....

![2015-03-23_12-27-52](https://cloud.githubusercontent.com/assets/6510026/6788634/1bed6d4c-d158-11e4-85b3-2b62f89ddb1a.png)

**Comment by marcelveldt** [comment]
Oh, that error is coming from the skinshortcuts script which tries to load playlists on all possible locations, has Always been that way and you can ignore...

I just checked in some changes to the smart shortcuts, should be a little less fail safe. Still no caching though but I want to give it a try first without. I should not load your connection or libraries because it only pulls 1 image at a time and only when you're on the homescreen.

**Comment by mgonzales71** [comment]
ok did a new build from Git and playlists were on by default, favorites off by default.

enabling favorites scan and restored my orig favorites file.

did you really mean it is "less" fail safe now then before? :)

running scan of favorites now...

if you want I can sent you log file after a few mins of letting it run.

i am getting alot of trakt timeout now from SALTS and U have already seen like 3 Genesis scan/updates hehe

will post back in a few

**Comment by marcelveldt** [comment]
I just saw your comment about the documentation...
Actually I'm planning for a while to start a thread on the forum with a general FAQ/howto.
I just don't find the time to get started with it...

Do you want to help with this ?
I'm thinking about the following: A thread called "general help/FAQ for Titan skin" or something.
Every post will be a different FAQ article and the first post will contain shortcuts to every detailed article. That way you have a quick oversight in the first article of every help subject and clicking on it will bring you directly to the post which contains the explaination or tip. I would like to encourage other users to place their tip there too, like how they use the skin or nice workarounds etc..

If you're interested in helping with this, it would be best if you create the thread. I can edit that post because I'm the moderator and you can edit it because you're the author of the origfinal post. That way we can both keep the thread/post up to date.
Please let me know your honoust answer if you'd like to help. No hard feelings if you don't have the time for that.

**Comment by mgonzales71** [comment]
I am seeing items show up from the favorites scan

![2015-03-23_12-54-26](https://cloud.githubusercontent.com/assets/6510026/6789209/f879940e-d15b-11e4-848f-512481001abe.png)

How about this as a solution:

For both Playlists and Favorites
have a scan frequency setting.

At Startup Only
or intervals of 15/30/45 mins 
or 1-12 hours.

I think having the user in control of the scan frequency will also allow users to manage expectations of how often smart shortcut items are updated

**Comment by mgonzales71** [comment]
regarding documentation - have you looked into - https://pages.github.com/ ?

**Comment by mgonzales71** [comment]
also - look at https://readthedocs.org/

forums as a documentation source / host - it gets messy fast,

but yea I am willing to help out.

I am sure if you posted on the feature request forum you could get others to also help out. 

obviously once you do have documentation online you can post links in the forum, the add-on read me and even have it accessible from the skin itself

**Comment by marcelveldt** [comment]
I'd like to have the docs on the forum itself to keep it as simple and accessible as possible, also the text will be search-able on the forums. That's why my idea of using the first post to just link to other articles.
This may as well be articles on github or any other source by the way but I thought the forums is just as convenient. It isn't a big-ass software solution or something ;-)

Playlist update frequency is currently set at 1 minute so each tile image/background will update every 1 minute. There's absolutely no harm in that scan every minute as it will only pull 1 item from every list so no huge data at all. 

When I have some time available I'll add some caching to this but in that case I have to pull in all items from the list/lists and store that in memory, I don't know which one is better. I think most users will use it together with playlists, the favourites is just a "nice to have" that I created while coding the first. For now users have to accept some background scanning of their favourites :-)

**Comment by mgonzales71** [comment]
it's not all quiet and in the Background - I am getting an in skin error from one of the add-ons over and over now because of timeouts and that is annoying. 

add to that Geneis telling me its "updating" and "scanning" and then "finished" over and over

LOL

i know you are not caching yet but I know the requests for being able to set this will probably come 
soon.

at least think about adding it :-)

next aired and other add-ons allow setting scan intervals - all the cool kids are doing it! ;)

I am going to have to turn it for now - the notifications are gonna make me crazy

I will re-test as this very cool feature matures.

**Comment by marcelveldt** [comment]
Please send me your logfile so I can look for more conditions that need to be taken care of. The problem is not the interval, the problem are those addons that error when they're opened in the background. I need to make some sort of black/whitelist from what I can scan and what not but I don't want any code in there for any illegal addons or something.

I've tried the feature myself (but I only have little addons) and that works great without errors.
If you could send me your logfile that would be great. I can then recondider if the caching is needed from the beginning..

**Comment by mgonzales71** [comment]
well I know for a fact that Genesis will give an "error" in the log file when alot of it's built in functions are called but the add-on works just fine.

so for example this "error":
"13:26:30 T:1068   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.genesis/?action=library_update_tool"

is normal for the Genesis Update Library command.

but would be something for your black list.

will users have control over the black and white lists?

log file:

http://pastebin.com/wWbbzBFr

**Comment by mgonzales71** [comment]
also not sure why the SALTS keeps getting called as well.

what this returns is a list of the progress of your tv episodes from trakt.tv

this add-on is one of the few if not the only one to support clear art/logs, etc

![screenshot000](https://cloud.githubusercontent.com/assets/6510026/6790603/1bda43f8-d166-11e4-9d08-16b6c4f252cd.png)

repeating log entry for this call from my favorites...

13:32:13 T:7728  NOTICE: Previous line repeats 4 times.
13:32:13 T:7728  NOTICE: Thread LanguageInvoker start, auto delete: false
13:32:14 T:7728  NOTICE: -->Python Interpreter Initialized<--
13:32:14 T:7728  NOTICE: URLResolver: Initializing URLResolver version: 2.8.0
13:32:15 T:7728  NOTICE: URLResolver: No Settings Update Needed
13:32:15 T:7728  NOTICE: Stream All The Sources: Version: |1.0.0~beta2| Queries: |{'mode': 'show_progress'}|
13:32:15 T:7728  NOTICE: Stream All The Sources: Args: |['plugin://plugin.video.salts/', '58', '?mode=show_progress']|
13:32:15 T:7728  NOTICE: Stream All The Sources: Calling |show_progress| for mode |show_progress| with pos args |[]| and kwargs |{}|
13:32:16 T:7728  NOTICE: Stream All The Sources: All progress results received

**Comment by marcelveldt** [comment]
OK, I went ahead and added the caching anyway :-)

I've also put in some detection for failing addons so it will automatically blacklist.
Only the first time you'll maybe have some errors but then no more.

Scanning a directory will only happen upon startup or when a new node is added to the favourites/playlists. Images will be retrieved every 60 seconds from the cache.

Beta is online BTW

**Comment by mgonzales71** [comment]
grabbing and then testing it here shortly - thanks sir.

any way to un-blacklist an add-on (text file, xml, etc) or does the blacklist get reset at every start up?

**Comment by marcelveldt** [comment]
Currently not needed to un-blacklist because only the failing subnode will be blacklisted... Give it a try and let me know!

**Comment by mgonzales71** [comment]
FYI - skin.titan.helix zip on the repo is corrupt

**Comment by mgonzales71** [comment]
the changes seem to have resolved the looping issue - right not trakt website is overloaded and throwing time outs - so I will need to wait to do another test when its back under load.

**Comment by mgonzales71** [comment]
ok did a 10 min test - the help scanned/called 2 add-ons and the function from each I created a favorite of.

in 10 mins - those add-on function calls used about 25 MB of network usage,

one thing I worry about with possibly calling and add-on so often is that a site called by the add-on may throttle your account or temporarily block your access mistaken so many frequent calls as a DoS attack, etc 

one add-on call can hit several sites like - imdb, trakt, tvdb, tvrage, etc every time - every minute,

Q - why every minute?  is that for the image change of the home menu tile?  or to scan for new media?

just something to consider  - ok - I am done beating this horse now :-) hehe

each update has improved this new and very cool feature - so I am not too worried 

I am eager to see what forum folks say when they test out Smart Shortcuts 

thanks again Marcel - you have by far the best skin for Kodi!

Mario

**Comment by marcelveldt** [comment]
Mario,

I'm afraid you didn't read my previous post well or it is my bad English :-)

I changed the whole logic and those addons are only scaped just ONCE upon Kodi startup.
It will then save all artwork found to a simple cache file and the images are retrieved from that cache file every minute.

So to be clear: the addons are definitely NOT called every minute.
