### ISSUE TITLE
bug?: extended info - missing titles / labels

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/xbmc.skin.titan#77]
various items (almost all) in the extended info display are missing titles for season, shows, episode, movies, character names, etc

![2015-06-01_02-08-18](https://cloud.githubusercontent.com/assets/6510026/7909831/27a61386-0804-11e5-8fcc-89d027376ea1.jpg)
![2015-06-01_02-08-42](https://cloud.githubusercontent.com/assets/6510026/7909834/27a942d6-0804-11e5-85aa-bc759bd75ab7.jpg)
![2015-06-01_02-09-20](https://cloud.githubusercontent.com/assets/6510026/7909832/27a6cca4-0804-11e5-9e0e-ba0584937aeb.png)
![2015-06-01_02-12-44](https://cloud.githubusercontent.com/assets/6510026/7909833/27a8b3e8-0804-11e5-8682-9ab0cd7ebaa4.jpg)

**Comment by marcelveldt** [comment]
Thanks for noticing.. I think this is caused by the fact that some elements do not accept the dynamic coloring...

Am already discussing it on the forums, others skinners have issues too but is seems to be ignored. If it is the same issue, I will just set the textcolor to white...

http://forum.kodi.tv/showthread.php?tid=203327&pid=2010718#pid2010718

**Comment by marcelveldt** [comment]
fixed.. I indeed had to change the textcolor to white to solve this..

**Comment by mgonzales71** [comment]
i wonder if this is what is causing addon settings to not display text label of (I believe they are) buttons

**Comment by marcelveldt** [comment]
yep, that is the same problem
